version: '3'

services:
    data-api:
        image: bhargodevarya/data-api:latest
        #build: ./data-api
        ports: 
            - "7070:7070"
        networks: 
            - backend
    dashboard:
        image: bhargodevarya/dashboard:latest
        #build: ./nodejs_dummy_project
        ports: 
            - "6060:6060"
        networks: 
            - backend
networks: 
    backend:
        name: 'backend'
    

